// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using anotherCalendarBe;

#nullable disable

namespace anotherCalendarBe.Migrations
{
    [DbContext(typeof(AnotherCDbContext))]
    [Migration("20230323063005_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("anotherCalendarBe.Models.AppConfig", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("production")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_id");

                    b.ToTable("AppConfig", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
