// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using anotherCalendarBe;

#nullable disable

namespace anotherCalendarBe.Migrations
{
    [DbContext(typeof(AnotherCDbContext))]
    [Migration("20230411195948_ce table")]
    partial class cetable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("anotherCalendarBe.Models.AppConfig", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_id");

                    b.ToTable("AppConfig");
                });

            modelBuilder.Entity("anotherCalendarBe.Models.CalendarEvent", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("endDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("startDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("_id");

                    b.ToTable("CalendarEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
