// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using anotherCalendarBe;

#nullable disable

namespace anotherCalendarBe.Migrations
{
    [DbContext(typeof(AnotherCDbContext))]
    partial class AnotherCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("anotherCalendarBe.Models.AppConfig", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("_id");

                    b.ToTable("AppConfig", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("648daff3-5940-400a-8f80-f9b8a2504241"),
                            version = "0.0.1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
